import type { Doc } from "@/convex/_generated/dataModel";
import { getRuleMeta } from "@/lib/rule-catalog";
import { getVerdictMessage, type VerdictLevel } from "@/lib/verdict-messages";

type Skill = Doc<"scannedSkills">;
type Language = "en" | "ru" | "es";

const LEVELS: Record<Language, Record<string, string>> = {
  en: {
    none: "Clean",
    low: "Low",
    medium: "Medium",
    elevated: "Elevated",
    high: "High",
    critical: "Critical",
  },
  ru: {
    none: "Чисто",
    low: "Низкий",
    medium: "Средний",
    elevated: "Повышенный",
    high: "Высокий",
    critical: "Критический",
  },
  es: {
    none: "Limpio",
    low: "Bajo",
    medium: "Medio",
    elevated: "Elevado",
    high: "Alto",
    critical: "Crítico",
  },
};

const RECOMMENDATIONS: Record<Language, Record<string, string>> = {
  en: {
    none: "Can be used",
    low: "Can be used; findings archived for reference",
    medium: "Use with restrictions (sandbox, no secrets, no network)",
    elevated: "Restricted use only (supervised runs, tight sandbox)",
    high: "Reject or apply strict restrictions",
    critical: "Reject",
  },
  ru: {
    none: "Можно использовать",
    low: "Можно использовать; находки зафиксированы",
    medium: "Использовать с ограничениями (песочница, без секретов, без сети)",
    elevated: "Только ограниченное использование (под присмотром, в песочнице)",
    high: "Отклонить либо жёсткие ограничения",
    critical: "Отклонить",
  },
  es: {
    none: "Se puede usar",
    low: "Se puede usar; hallazgos archivados como referencia",
    medium: "Usar con restricciones (sandbox, sin secretos, sin red)",
    elevated: "Solo uso restringido (bajo supervisión, en sandbox)",
    high: "Rechazar o aplicar restricciones estrictas",
    critical: "Rechazar",
  },
};

const T: Record<Language, Record<string, string>> = {
  en: {
    title: "Skill assessment protocol",
    finalScore: "Final score",
    recommendation: "Recommendation",
    passport: "Passport",
    name: "Name",
    kind: "Kind",
    description: "Description",
    assessedAt: "Assessed at",
    method: "Method",
    scannerResult: "Scanner result",
    breakdown: "Score breakdown",
    noRules: "- No rules triggered → final score: **0**",
    maxWeight: "Max rule weight",
    triggeredRules: "Triggered rules",
    stackingBonus: "stacking bonus",
    cap6per: "6 per extra rule, cap 24",
    scoreCap: "Score cap",
    byFormula: "By formula",
    calibrationNote: "(actual score differs — deployment uses its own calibration)",
    rule: "Rule",
    weight: "Weight",
    evidence: "Evidence",
    verdict: "Verdict",
    level: "Level",
    confidenceLabel: "Confidence",
    confidence: "medium (static analysis)",
    findingsNote:
      "> Findings are signals, not verdicts. The final call is human: review the quoted evidence.",
    generatedBy: "Generated by Skill-scanner v1",
    methodologyHash: "methodology 1.0",
    scannerName: "Skill-scanner v1",
  },
  ru: {
    title: "Протокол оценки навыка",
    finalScore: "Итоговый скор",
    recommendation: "Рекомендация",
    passport: "Паспорт",
    name: "Название",
    kind: "Тип",
    description: "Описание",
    assessedAt: "Дата оценки",
    method: "Методика",
    scannerResult: "Результат сканера",
    breakdown: "Разброс оценки",
    noRules: "- Сработавших правил нет → итоговый скор: **0**",
    maxWeight: "Максимальный вес правила",
    triggeredRules: "Сработавших правил",
    stackingBonus: "стекинг-бонус",
    cap6per: "6 × доп. правила, потолок 24",
    scoreCap: "Кап оценки",
    byFormula: "По формуле",
    calibrationNote: "(фактический скор отличается — деплой использует свою калибровку)",
    rule: "Правило",
    weight: "Вес",
    evidence: "Цитаты",
    verdict: "Вердикт",
    level: "Уровень",
    confidenceLabel: "Уверенность",
    confidence: "средняя (статический анализ)",
    findingsNote:
      "> Находки — сигналы, а не приговор. Итоговое решение за человеком: проверьте цитаты вручную.",
    generatedBy: "Сгенерировано «Скилл-сканером» v1",
    methodologyHash: "хэш методики 1.0",
    scannerName: "Скилл-сканер v1",
  },
  es: {
    title: "Protocolo de evaluación de skill",
    finalScore: "Puntuación final",
    recommendation: "Recomendación",
    passport: "Pasaporte",
    name: "Nombre",
    kind: "Tipo",
    description: "Descripción",
    assessedAt: "Fecha de evaluación",
    method: "Metodología",
    scannerResult: "Resultado del escáner",
    breakdown: "Desglose de la puntuación",
    noRules: "- Ninguna regla activada → puntuación final: **0**",
    maxWeight: "Peso máximo de regla",
    triggeredRules: "Reglas activadas",
    stackingBonus: "bono de apilamiento",
    cap6per: "6 × reglas extra, tope 24",
    scoreCap: "Tope de puntuación",
    byFormula: "Por fórmula",
    calibrationNote: "(la puntuación real difiere — el despliegue usa su propia calibración)",
    rule: "Regla",
    weight: "Peso",
    evidence: "Evidencia",
    verdict: "Veredicto",
    level: "Nivel",
    confidenceLabel: "Confianza",
    confidence: "media (análisis estático)",
    findingsNote:
      "> Los hallazgos son señales, no veredictos. La decisión final es humana: revisa la evidencia citada.",
    generatedBy: "Generado por Skill-scanner v1",
    methodologyHash: "hash de metodología 1.0",
    scannerName: "Skill-scanner v1",
  },
};

const METHOD_URL = "https://github.com/symmora/skill-scanner-pro/blob/main/docs/skill-assessment-protocol.md";

/**
 * Builds the assessment protocol (Markdown) for a scanned skill.
 * The final score is placed first — it is the headline of the document.
 */
export function buildAssessmentProtocol(skill: Skill, language: Language): string {
  const t = T[language];
  const level = LEVELS[language][skill.riskLevel] ?? skill.riskLevel;
  const recommendation = RECOMMENDATIONS[language][skill.riskLevel] ?? "";
  const date = new Date(skill.analyzedAt).toISOString().replace("T", " ").slice(0, 16) + " UTC";

  const lines: string[] = [];

  const verdictMsg = getVerdictMessage(
    skill.riskLevel as VerdictLevel,
    language,
    skill.name,
  );
  // ── Headline: the final score first ──────────────────────────────────
  lines.push(`# ${t.title}`);
  lines.push("");
  lines.push(`## ${t.finalScore}: ${skill.riskScore} / 100 — ${level}`);
  lines.push("");
  lines.push(`> ${verdictMsg}`);
  lines.push("");
  lines.push(`${t.recommendation}: **${recommendation}**`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // ── Passport ─────────────────────────────────────────────────────────
  lines.push(`## ${t.passport}`);
  lines.push("");
  lines.push(`- ${t.name}: ${skill.name}`);
  lines.push(`- ${t.kind}: ${skill.kind}`);
  if (skill.description) {
    lines.push(`- ${t.description}: ${skill.description}`);
  }
  lines.push(`- ${t.assessedAt}: ${date}`);
  lines.push(`- ${t.method}: ${t.scannerName} (${METHOD_URL})`);
  lines.push("");

  // ── Scanner result ───────────────────────────────────────────────────
  lines.push(`## ${t.scannerResult}`);
  lines.push("");

  // ── Score breakdown: several scores, so the final number is never a black box ──
  const sorted = [...skill.findings].sort((a, b) => b.severity - a.severity);
  const maxWeight = sorted[0]?.severity ?? 0;
  const maxRule = sorted[0]?.ruleId ?? "—";
  const extraRules = Math.max(0, skill.findings.length - 1);
  const bonus = Math.min(24, extraRules * 6);
  const byFormula = Math.min(100, maxWeight + bonus);

  lines.push(`### ${t.breakdown}`);
  lines.push("");
  if (skill.findings.length === 0) {
    lines.push(t.noRules);
  } else {
    lines.push(`- ${t.maxWeight}: **${maxWeight}** (\`${maxRule}\`)`);
    lines.push(
      `- ${t.triggeredRules}: **${skill.findings.length}** → ${t.stackingBonus}: **+${bonus}** (${t.cap6per})`,
    );
    lines.push(`- ${t.scoreCap}: 100`);
    lines.push(
      `- ${t.byFormula}: ${maxWeight} + ${bonus} = **${byFormula}**${byFormula === skill.riskScore ? "" : ` ${t.calibrationNote}`}`,
    );
  }
  lines.push("");
  lines.push(`| # | ${t.rule} | ID | ${t.weight} | ${t.evidence} |`);
  lines.push("|---|---|---|---|---|");
  skill.findings.forEach((f, i) => {
    const meta = getRuleMeta(f.ruleId);
    const title = meta ? meta.title[language] : f.ruleId;
    // Plain-Markdown separator — no HTML tags inside table cells.
    const evidence = f.evidence.length > 0 ? f.evidence.map((e) => `\`${e.replace(/`/g, "'")}\``).join(" · ") : "—";
    lines.push(`| ${i + 1} | ${title} | \`${f.ruleId}\` | ${f.severity} | ${evidence} |`);
  });
  lines.push("");

  // ── Verdict ──────────────────────────────────────────────────────────
  lines.push(`## ${t.verdict}`);
  lines.push("");
  lines.push(`- ${t.level}: **${level}** (${skill.riskScore} / 100)`);
  lines.push(`- ${t.confidenceLabel}: ${t.confidence}`);
  lines.push(`- ${t.recommendation}: **${recommendation}**`);
  lines.push("");
  lines.push(t.findingsNote);
  lines.push("");
  lines.push(`---`);
  lines.push(
    `*${t.generatedBy} · ${date} · ${t.methodologyHash}*`,
  );

  return lines.join("\n");
}

/** Downloads the protocol as a .md file. */
export function downloadAssessmentProtocol(skill: Skill, language: Language): void {
  const md = buildAssessmentProtocol(skill, language);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `protocol-${skill.name.replace(/[^a-zA-Z0-9_-]+/g, "_")}-${skill.riskScore}.md`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
